<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>turtlesim_basics</name>
  <version>0.1.0</version>
  <description>turtlesim 으로 익히는 ROS 2 기초: Topic(pub/sub) 과 Service(client/server)</description>
  <maintainer email="howard.jeong@theplatforms.io">howard.jeong</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>turtlesim</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
